pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                sh '''
                cd "Repository-name-two-tier-flask-app using docker and jenkins"
                docker build -t flask-app:latest .
                '''
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                sh '''
                cd "Repository-name-two-tier-flask-app using docker and jenkins"
                docker-compose down || true
                docker-compose up -d --build
                '''
            }
        }
    }
}
